---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---
```{r}
echo = TRUE

library(lattice)
library(plyr)
```

## Loading and preprocessing the data
```{r}
data <- read.csv("activity.csv")
```

## What is mean total number of steps taken per day?
```{r}
totalSteps <- ddply(data, "date", summarize, numSteps = sum(steps))
hist(totalSteps$numSteps
     , main = "Total Steps"
     , xlab = "Total Steps")

meanSteps <- mean(totalSteps$numSteps, na.rm = TRUE)
medianSteps <- median(totalSteps$numSteps, na.rm = TRUE)

meanSteps
medianSteps
```


## What is the average daily activity pattern?
```{r}
dailyPattern <- ddply(data, "interval", summarize, avgSteps = mean(steps, na.rm = TRUE))
plot(dailyPattern$avgSteps
     , type = "l"
     , main = "Daily Steps"
     , xlab = "5-Minute Increments"
     , ylab = "Avg Number of Steps per Day"
     , col = "blue"
     , xaxt = "n")
axis(1, 1:nrow(dailyPattern),dailyPattern$interval)

maxInterval <- dailyPattern[dailyPattern$inerval == max(dailyPattern$interval),]
maxInterval
```


## Imputing missing values
```{r}
numNA <- sum(is.na(data$steps))
numNA
noNAData <- data
noNAData$steps[is.na(noNAData$steps)] <- 0
noNATotalSteps <- ddply(noNAData, "date", summarize, numSteps = sum(steps))
hist(noNATotalSteps$numSteps
     , main = "Total Steps Without NAs"
     , xlab = "Total Steps Without NAs")


noNAMean <- mean(noNAData$steps)
noNAMedian <- median(noNAData$steps)
noNAMean
noNAMedian
```


## Are there differences in activity patterns between weekdays and weekends?
```{r}
data$date <- as.POSIXlt(data$date, format = "%Y-%m-%d")
data$day <- weekdays(data$date)
data$typeDay <- ifelse(data$day == "Saturday" | data$day == "Sunday"
                       , "Weekend"
                       , "weekday")
data$typeDay <- factor(data$typeDay)


weekdayGroups <- ddply(data
                       , ~interval + typeDay
                       , summarise
                       , mean = mean(steps, na.rm=TRUE))

weekdayGroups$interval <- as.numeric(as.character(weekdayGroups$interval))
xyplot(mean ~ interval | typeDay
       , weekdayGroups
       , type = "l"
       , layout = c(1, 2)
       , xlab = "Interval"
       , ylab = "Number of steps")
```
